#!/bin/sh
#
# Stage the Claudezilla file tree into a packaging root.
#
# Every package recipe calls this instead of repeating the layout, so adding a
# file to the install set is a one-line change here rather than the same change
# in a dozen distro recipes that are easy to let drift.
#
# Run from anywhere, after the recipe's build step has produced
# `mcp/node_modules` and `claudezilla.xpi` in the source root.
#
#   DESTDIR=/path/to/staging packaging/common/install-tree.sh
#
# Knobs, all optional:
#
#   PREFIX        install prefix                    (default /usr)
#   LIBDIR        private library directory         (default $PREFIX/lib/claudezilla)
#   BINDIR        executables                       (default $PREFIX/bin)
#   MOZDIR        system-wide native messaging      (default $PREFIX/lib/mozilla/native-messaging-hosts)
#   UNITDIR       systemd user units                (default $PREFIX/lib/systemd/user)
#   DOCDIR        documentation                     (default $PREFIX/share/doc/claudezilla)
#   LICENSEDIR    license                           (default $PREFIX/share/licenses/claudezilla)
#   NODE_BIN      fallback runtime in the launchers (default /usr/bin/node)
#   WITH_SYSTEMD  install the browser service       (default 1; set 0 on macOS)
#   WITH_MOZDIR   install the system-wide manifest  (default 1; set 0 where
#                 Firefox reads only per-user paths, e.g. Homebrew on macOS)

set -eu

: "${DESTDIR:?DESTDIR must be set}"
PREFIX="${PREFIX:-/usr}"
LIBDIR="${LIBDIR:-$PREFIX/lib/claudezilla}"
BINDIR="${BINDIR:-$PREFIX/bin}"
MOZDIR="${MOZDIR:-$PREFIX/lib/mozilla/native-messaging-hosts}"
UNITDIR="${UNITDIR:-$PREFIX/lib/systemd/user}"
DOCDIR="${DOCDIR:-$PREFIX/share/doc/claudezilla}"
LICENSEDIR="${LICENSEDIR:-$PREFIX/share/licenses/claudezilla}"
NODE_BIN="${NODE_BIN:-/usr/bin/node}"
WITH_SYSTEMD="${WITH_SYSTEMD:-1}"
WITH_MOZDIR="${WITH_MOZDIR:-1}"

src="$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)"
cd "$src"

[ -d mcp/node_modules ] || { echo "install-tree: mcp/node_modules missing — run the build step first" >&2; exit 1; }
[ -f claudezilla.xpi ] || { echo "install-tree: claudezilla.xpi missing — run the build step first" >&2; exit 1; }

mkdir -p "$DESTDIR$LIBDIR/host" "$DESTDIR$LIBDIR/mcp" "$DESTDIR$BINDIR" \
    "$DESTDIR$DOCDIR" "$DESTDIR$LICENSEDIR"

# Native messaging host — no runtime dependencies of its own.
for f in index.js ipc.js protocol.js cli.js package.json; do
    cp host/"$f" "$DESTDIR$LIBDIR/host/$f"
    chmod 644 "$DESTDIR$LIBDIR/host/$f"
done

# MCP server, with dependencies vendored by the recipe's build step.
for f in server.js package.json; do
    cp mcp/"$f" "$DESTDIR$LIBDIR/mcp/$f"
    chmod 644 "$DESTDIR$LIBDIR/mcp/$f"
done
cp -R mcp/node_modules "$DESTDIR$LIBDIR/mcp/node_modules"

# Extension, sideloaded into the headless profile by claudezilla-setup.
cp claudezilla.xpi "$DESTDIR$LIBDIR/claudezilla.xpi"
chmod 644 "$DESTDIR$LIBDIR/claudezilla.xpi"

# Launchers. The runtime is chosen at exec time rather than baked in: an
# explicit $CLZ_RUNTIME wins, then bun if the user happens to have it, then the
# packaged nodejs dependency. Bun is never required.
for pair in host:index.js mcp:server.js; do
    component="${pair%%:*}"
    entry="${pair#*:}"
    target="$DESTDIR$BINDIR/claudezilla-$component"
    cat > "$target" <<EOF
#!/bin/sh
# Generated by packaging/common/install-tree.sh — do not edit.
if [ -n "\${CLZ_RUNTIME:-}" ] && [ -x "\$CLZ_RUNTIME" ]; then
    exec "\$CLZ_RUNTIME" $LIBDIR/$component/$entry "\$@"
fi
if command -v bun >/dev/null 2>&1; then
    exec bun $LIBDIR/$component/$entry "\$@"
fi
exec $NODE_BIN $LIBDIR/$component/$entry "\$@"
EOF
    chmod 755 "$target"
done

cp packaging/common/claudezilla-setup "$DESTDIR$BINDIR/claudezilla-setup"
chmod 755 "$DESTDIR$BINDIR/claudezilla-setup"

# System-wide native messaging manifest. Generated rather than copied so the
# path tracks $BINDIR instead of assuming /usr/bin.
if [ "$WITH_MOZDIR" = "1" ]; then
    mkdir -p "$DESTDIR$MOZDIR"
    cat > "$DESTDIR$MOZDIR/claudezilla.json" <<EOF
{
  "name": "claudezilla",
  "description": "Claude Code Firefox browser automation bridge",
  "path": "$BINDIR/claudezilla-host",
  "type": "stdio",
  "allowed_extensions": ["claudezilla@boot.industries"]
}
EOF
    chmod 644 "$DESTDIR$MOZDIR/claudezilla.json"
fi

if [ "$WITH_SYSTEMD" = "1" ]; then
    mkdir -p "$DESTDIR$UNITDIR"
    cp packaging/common/claudezilla-browser.service "$DESTDIR$UNITDIR/claudezilla-browser.service"
    chmod 644 "$DESTDIR$UNITDIR/claudezilla-browser.service"
fi

cp LICENSE "$DESTDIR$LICENSEDIR/LICENSE"
chmod 644 "$DESTDIR$LICENSEDIR/LICENSE"
cp README.md "$DESTDIR$DOCDIR/README.md"
chmod 644 "$DESTDIR$DOCDIR/README.md"
