# shellcheck shell=bash
#
# Shared helpers for the Claudezilla installers.
#
# install-macos.sh and install-linux.sh differ only in their platform paths and
# the extra Linux steps (headless profile, systemd unit); the host wrapper,
# native manifest, and MCP dependency install were duplicated line-for-line.
# They live here so a change to any of them happens once.

# Locate a JavaScript runtime, preferring Bun when it is installed and falling
# back to Node.js. Node.js remains the only required runtime — Bun is used
# opportunistically, for its faster startup.
#
# GUI-launched Firefox and the Claude Code desktop app do not inherit the
# user's shell PATH, so a PATH lookup alone is not enough; the usual install
# prefixes are checked too. $CLZ_RUNTIME overrides the choice entirely.
clz_find_runtime() {
    local candidate
    for candidate in \
        "${CLZ_RUNTIME:-}" \
        "${BUN_INSTALL:+$BUN_INSTALL/bin/bun}" \
        "$(command -v bun 2>/dev/null)" \
        "$HOME/.bun/bin/bun" \
        "/opt/homebrew/bin/bun" \
        "/usr/local/bin/bun" \
        "/usr/bin/bun" \
        "$(command -v node 2>/dev/null)" \
        "/opt/homebrew/bin/node" \
        "/usr/local/bin/node" \
        "/usr/bin/node"
    do
        if [ -n "$candidate" ] && [ -x "$candidate" ]; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

clz_require_runtime() {
    local runtime
    if ! runtime="$(clz_find_runtime)"; then
        echo "Error: no JavaScript runtime found — install Node.js 18+ (or Bun)." >&2
        echo "       Node.js: https://nodejs.org/" >&2
        echo "       Bun:     curl -fsSL https://bun.sh/install | bash" >&2
        echo "       Or set CLZ_RUNTIME=/path/to/runtime and re-run this installer." >&2
        return 1
    fi
    printf '%s\n' "$runtime"
}

# clz_write_wrapper <wrapper-path> <entry-filename> <runtime-path>
#
# Writes the launcher that Firefox and Claude Code execute. It resolves the
# checkout from its own location rather than hardcoding it, and repeats the
# runtime search at launch so that installing or removing Bun later does not
# require re-running the installer. The install-time choice is tried first.
# <entry-filename> is relative to the wrapper's own directory.
clz_write_wrapper() {
    local wrapper_path="$1" entry="$2" runtime_path="$3"

    cat > "$wrapper_path" << WRAPPER_EOF
#!/bin/bash
# Generated by the Claudezilla installer — do not edit.

CLZ_RUNTIME_DEFAULT="$runtime_path"
CLZ_ENTRY="$entry"
WRAPPER_EOF

    # Quoted heredoc: this half must reach the wrapper verbatim.
    cat >> "$wrapper_path" << 'WRAPPER_EOF'

# Resolve this script's real directory, following symlinks.
self="${BASH_SOURCE[0]}"
while [ -L "$self" ]; do
    target="$(readlink "$self")"
    case "$target" in
        /*) self="$target" ;;
        *)  self="$(dirname "$self")/$target" ;;
    esac
done
dir="$(cd "$(dirname "$self")" && pwd)"

runtime=""
for candidate in \
    "${CLZ_RUNTIME:-}" \
    "$CLZ_RUNTIME_DEFAULT" \
    "${BUN_INSTALL:+$BUN_INSTALL/bin/bun}" \
    "$(command -v bun 2>/dev/null)" \
    "$HOME/.bun/bin/bun" \
    "/opt/homebrew/bin/bun" \
    "/usr/local/bin/bun" \
    "/usr/bin/bun" \
    "$(command -v node 2>/dev/null)" \
    "/opt/homebrew/bin/node" \
    "/usr/local/bin/node" \
    "/usr/bin/node"
do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
        runtime="$candidate"
        break
    fi
done

if [ -z "$runtime" ]; then
    echo "claudezilla: no JavaScript runtime found — install Node.js or Bun, or set \$CLZ_RUNTIME" >&2
    exit 1
fi

exec "$runtime" "$dir/$CLZ_ENTRY" "$@"
WRAPPER_EOF

    chmod 755 "$wrapper_path"
}

# clz_write_manifest <native-hosts-dir> <wrapper-path>
#
# Writes the native messaging manifest into a browser's hosts directory.
# SECURITY: manifest permissions are set explicitly.
clz_write_manifest() {
    local hosts_dir="$1" wrapper_path="$2"

    mkdir -p "$hosts_dir"
    cat > "$hosts_dir/claudezilla.json" << MANIFEST_EOF
{
  "name": "claudezilla",
  "description": "Claude Code Firefox browser automation bridge",
  "path": "$wrapper_path",
  "type": "stdio",
  "allowed_extensions": ["claudezilla@boot.industries"]
}
MANIFEST_EOF
    chmod 644 "$hosts_dir/claudezilla.json"
}

# clz_install_mcp_deps <mcp-dir>
#
# Prefers Bun when present, so a Bun-only machine can install without npm.
clz_install_mcp_deps() {
    local mcp_dir="$1" bun

    bun="$(command -v bun 2>/dev/null || true)"
    if [ -n "$bun" ] && [ -x "$bun" ]; then
        echo "Installing MCP dependencies with Bun..."
        (cd "$mcp_dir" && "$bun" install --ignore-scripts)
        return
    fi

    if command -v npm >/dev/null 2>&1; then
        echo "Installing MCP dependencies..."
        (cd "$mcp_dir" && npm install --quiet --ignore-scripts)
        return
    fi

    echo "Error: neither bun nor npm found — cannot install MCP dependencies." >&2
    return 1
}
